---
version: "3.8"

services:
  skyname:
    container_name: skyname
    image: ghcr.io/darnfish/skyname:main
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      SKYNAME_CONFIG: "<skyname_config>"
      POSTGRES_URL: "postgres://skyname:<postgres_password>@skyname-postgres/skyname"
      # TG_BOT_TOKEN: ""
      # TG_CHAT_ID: ""
    depends_on:
      - skyname-postgres
    networks:
      - skyname
  skyname-postgres:
    container_name: skyname-postgres
    image: postgres
    restart: unless-stopped
    volumes:
      - "/your/data/dir:/var/lib/postgresql/data:rw"
    environment:
      POSTGRES_DB: "skyname"
      POSTGRES_USER: "skyname"
      POSTGRES_PASSWORD: "<postgres_password>"
    networks:
      - skyname
networks:
  skyname:
